# Docker Compose file WITHOUT persistent volumes (for testing/CI)
# Usage: docker compose -f docker-compose.yml -f docker-compose-no-volumes.yml up -d
#
# This file removes all volume mounts for ephemeral testing
# Data will be LOST when containers are removed

services:
  gateway:
    volumes: []

  frontend:
    volumes: []

  backend:
    volumes: []

  db:
    volumes: []

  db-replic:
    volumes: []

  dns:
    volumes: []

  portainer:
    volumes:
      # Keep docker socket (required for Portainer to work)
      - /var/run/docker.sock:/var/run/docker.sock

# Override all volumes to be ephemeral (no named volumes)
volumes:
  openmrs-frontend:
    driver_opts:
      type: tmpfs
      device: tmpfs
  openmrs-data:
    driver_opts:
      type: tmpfs
      device: tmpfs
  db-data:
    driver_opts:
      type: tmpfs
      device: tmpfs
  db-backup:
    driver_opts:
      type: tmpfs
      device: tmpfs
  db-data-r:
    driver_opts:
      type: tmpfs
      device: tmpfs
  db-backup-r:
    driver_opts:
      type: tmpfs
      device: tmpfs
  gateway-data:
    driver_opts:
      type: tmpfs
      device: tmpfs
  portainer-data:
    driver_opts:
      type: tmpfs
      device: tmpfs
  pihole-data:
    driver_opts:
      type: tmpfs
      device: tmpfs
  pihole-dnsmaq:
    driver_opts:
      type: tmpfs
      device: tmpfs
