# Docker Compose override file for SSL/HTTPS configuration
# Usage: docker compose -f docker-compose.yml -f docker-compose-prod.yml -f docker-compose.ssl.yml up
#
# This file adds SSL support to the peruHCE distribution using self-signed certificates
# suitable for internal hospital networks.

services:
  # Certificate management service
  certbot:
    container_name: peruHCE-certbot
    build:
      context: ./certbot
      dockerfile: Dockerfile
    restart: "unless-stopped"
    environment:
      # SSL Mode: 'dev' for one-time generation, 'prod' for auto-renewal daemon
      SSL_MODE: ${SSL_MODE:-dev}

      # Certificate configuration
      CERT_WEB_DOMAINS: ${CERT_WEB_DOMAINS:-localhost,127.0.0.1,192.168.0.200,sihsalus.hsc,openmrs.sihsalus.hsc}
      CERT_WEB_DOMAIN_COMMON_NAME: ${CERT_WEB_DOMAIN_COMMON_NAME:-sihsalus.hsc}

      # Certificate parameters
      CERT_RSA_KEY_SIZE: ${CERT_RSA_KEY_SIZE:-4096}
      CERT_TEMP_CERT_DAYS: ${CERT_TEMP_CERT_DAYS:-365}
      CERT_RENEWAL_INTERVAL: ${CERT_RENEWAL_INTERVAL:-30d}

      # Organization details
      CERT_ORG: ${CERT_ORG:-Centro de Salud Santa Clotilde}
      CERT_OU: ${CERT_OU:-sihsalus}
      CERT_COUNTRY: ${CERT_COUNTRY:-PE}
      CERT_STATE: ${CERT_STATE:-Loreto}
      CERT_LOCALITY: ${CERT_LOCALITY:-Maynas}

    volumes:
      - letsencrypt-data:/etc/letsencrypt:rw
      - certbot-data:/var/www/certbot:rw

  # Gateway with SSL support
  gateway:
    environment:
      # Enable SSL configuration
      CERT_WEB_DOMAIN_COMMON_NAME: ${CERT_WEB_DOMAIN_COMMON_NAME:-sihsalus.hsc}
    volumes:
      # Mount certificate directories
      - letsencrypt-data:/etc/letsencrypt:ro
      - certbot-data:/var/www/certbot:rw
    depends_on:
      - certbot

volumes:
  # Volume for SSL certificates
  letsencrypt-data:
    name: peruHCE-letsencrypt-data

  # Volume for certbot web challenges and signals
  certbot-data:
    name: peruHCE-certbot-data
