version: "3.8"

services:
  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
      args:
        KEYCLOAK_VERSION:   ${KEYCLOAK_VERSION}
    env_file:
      - ./.env
    ports:
      - "${KEYCLOAK_PORT}:8080"
    volumes:
      - ./keycloak/themes:/opt/keycloak/themes:ro
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres:15
    env_file:
      - ./.env
    environment:
      POSTGRES_DB:       ${KC_DB_DATABASE}
      POSTGRES_USER:     ${KC_DB_USERNAME}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    volumes:
      - keycloak-data:/var/lib/postgresql/data

  portainer:
    container_name: peruHCE-portainer
    image: portainer/portainer-ce:lts
    command: -H unix:///var/run/docker.sock --http-enabled --base-url=/portainer
    restart: unless-stopped
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data

  gateway:
    container_name: peruHCE-gateway
    image: openmrs/openmrs-reference-application-3-gateway:${TAG}
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  frontend:
    container_name: peruHCE-frontend
    image: openmrs/openmrs-reference-application-3-frontend:${TAG}
    restart: unless-stopped
    environment:
      SPA_PATH:           /openmrs/spa
      API_URL:            /openmrs
      SPA_CONFIG_URLS:    /openmrs/spa/config-openmrs.json,/openmrs/spa/config-pucp.json
      SPA_DEFAULT_LOCALE: es
    depends_on:
      - backend
    volumes:
      - openmrs-frontend:/usr/share/nginx/html/

  backend:
    container_name: peruHCE-backend
    image: openmrs/openmrs-reference-application-3-backend:${TAG}
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      ENABLE_SSO:                   "true"
      OMRS_CONFIG_MODULE_WEB_ADMIN: "true"
      OMRS_CONFIG_AUTO_UPDATE_DATABASE: "true"
      OMRS_CONFIG_CREATE_TABLES:     "true"
      OMRS_CONFIG_CONNECTION_SERVER: db
      OMRS_CONFIG_CONNECTION_DATABASE: openmrs
      OMRS_CONFIG_CONNECTION_USERNAME: ${OMRS_DB_USER}
      OMRS_CONFIG_CONNECTION_PASSWORD: ${OMRS_DB_PASSWORD}
      OMRS_OCL_TOKEN:               ${OMRS_OCL_TOKEN}
    healthcheck:
      test:    ["CMD", "curl", "-f", "http://localhost:8080/openmrs"]
      timeout: 5s
    volumes:
      - openmrs-data:/openmrs/data
      - ./keycloak/oauth2.properties:/openmrs/app/data/oauth2.properties:ro
    depends_on:
      - db-replic
      - keycloak

  db:
    container_name: peruHCE-db-master
    image: mariadb:10.11.7
    restart: unless-stopped
    command: >
      mysqld
      --character-set-server=utf8mb3
      --collation-server=utf8mb3_general_ci
      --server-id=1
      --log-bin=mysql-bin
      --binlog-format=ROW
      --sync-binlog=1
      --log-slave-updates=1
    healthcheck:
      test:    mysql --user=${OMRS_DB_USER} --password=${OMRS_DB_PASSWORD} --execute "SHOW DATABASES;"
      interval: 3s
      timeout: 1s
      retries: 5
    environment:
      MYSQL_DATABASE:         openmrs
      MYSQL_USER:             ${OMRS_DB_USER}
      MYSQL_PASSWORD:         ${OMRS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD:    ${MYSQL_ROOT_PASSWORD}
      OMRS_DB_REPL_USER:      ${OMRS_DB_REPL_USER}
      OMRS_DB_REPL_PASSWORD:  ${OMRS_DB_REPL_PASSWORD}
      OMRS_DB_BACKUP_USER:    ${OMRS_DB_BACKUP_USER}
      OMRS_DB_BACKUP_PASSWORD:  ${OMRS_DB_BACKUP_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ./db-config/init-master.sh:/docker-entrypoint-initdb.d/init-master.sh
      - db-data:/var/lib/mysql
      - db-backup:/backup

  db-replic:
    container_name: peruHCE-db-replic
    image: mariadb:10.11.7
    restart: unless-stopped
    command: >
      mysqld
      --character-set-server=utf8mb3
      --collation-server=utf8mb3_general_ci
      --server-id=2
      --log-bin=mysql-bin
      --binlog-format=ROW
      --sync-binlog=1
      --log-slave-updates=1
      --read-only=1
    healthcheck:
      test:    mysql --user=${OMRS_DB_USER} --password=${OMRS_DB_PASSWORD} --execute "SHOW DATABASES;"
      interval: 3s
      timeout: 1s
      retries: 5
    depends_on:
      - db
    ports:
      - "3308:3306"
    volumes:
      - ./db-config/init-slave.sh:/docker-entrypoint-initdb.d/init-slave.sh
      - db-data-r:/var/lib/mysql
      - db-backup-r:/backup

  dns:
    container_name: peruHCE-dns
    image: pihole/pihole:2025.03.0
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "81:80/tcp"
      - "444:443/tcp"
    env_file:
      - ./.env
    environment:
      TZ:                              'America/Lima'
      FTLCONF_webserver_api_password: ${DNS_PASSWORD}
      FTLCONF_dns_listeningMode:      'all'
    volumes:
      - pihole-data:/etc/pihole
      - pihole-dnsmaq:/etc/dnsmasq.d

  fua-generator-db:
    container_name: peruHCE-fua-generator-db
    image: postgres:15
    ports:
      - "5433:5432"
    env_file:
      - ./.env
    environment:
      POSTGRES_USER:     ${PERUHCE_FUA_GEN_DB_USER}
      POSTGRES_PASSWORD: ${PERUHCE_FUA_GEN_DB_PASSWORD}
      POSTGRES_DB:       ${PERUHCE_FUA_GEN_DB}
    volumes:
      - db-fua-generator:/var/lib/postgresql/data

  fua-generator:
    container_name: peruHCE-fua-generator
    image: marcelius733/fua-generator:dev-0.1.2
    restart: unless-stopped
    ports:
      - "3333:3000"
    env_file:
      - ./.env
    environment:
      DB_USER:     ${PERUHCE_FUA_GEN_DB_USER}
      DB_PASSWORD: ${PERUHCE_FUA_GEN_DB_PASSWORD}
      DB_NAME:     ${PERUHCE_FUA_GEN_DB}
      DB_HOST:     peruHCE-fua-generator-db
      DB_PORT:     '5432'
      TOKEN:       ${PERUHCE_FUA_GEN_TOKEN}
    depends_on:
      - fua-generator-db

volumes:
  keycloak-data:
  portainer-data:
  openmrs-frontend:
  openmrs-data:
  db-data:
  db-backup:
  db-data-r:
  db-backup-r:
  pihole-data:
  pihole-dnsmaq:
  db-fua-generator:
