version: "3.8"

services:
  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
      args:
        KEYCLOAK_VERSION: ${KEYCLOAK_VERSION}
        KEYCLOAK_REALM:     ${KEYCLOAK_REALM}
        OIDC_CLIENT_ID:     ${OIDC_CLIENT_ID}
        OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
        KC_HOSTNAME:        ${KC_HOSTNAME}
        OPENMRS_PORT:       ${OPENMRS_PORT}
    env_file:
      - ./.env
    ports:
      - "${KEYCLOAK_PORT}:8080"
    volumes:
      - ./keycloak/themes:/opt/keycloak/themes:ro
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres:15
    env_file:
      - ./.env
    environment:
      POSTGRES_DB:       ${KC_DB_DATABASE}
      POSTGRES_USER:     ${KC_DB_USERNAME}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    volumes:
      - keycloak-data:/var/lib/postgresql/data

volumes:
  keycloak-data:
