version: "3.7"

services:
  backend:
    image: openmrs/openmrs-reference-application-3-backend:${TAG:-nightly}
    depends_on:
      - db
    secrets:
      - mysql_openmrs_password
    environment:
      OMRS_CONFIG_MODULE_WEB_ADMIN: "true"
      OMRS_CONFIG_AUTO_UPDATE_DATABASE: "true"
      OMRS_CONFIG_CREATE_TABLES: "true"
      OMRS_CONFIG_CONNECTION_SERVER: db
      OMRS_CONFIG_CONNECTION_DATABASE: openmrs
      OMRS_CONFIG_CONNECTION_USERNAME: ${OMRS_DB_USER:-openmrs}
      OMRS_CONFIG_CONNECTION_PASSWORD_FILE: /run/secrets/mysql_openmrs_password
      OMRS_OCL_TOKEN: ${OMRS_OCL_TOKEN:-openmrs}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/openmrs" ]
      timeout: 5s
    ports:
      - 8080:8080

  db:
    image: mariadb:11.8
    command: "mariadbd --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --server-id=1 --log-bin=mysql-bin --binlog-format=ROW --sync-binlog=1 --log-slave-updates=1"
    secrets:
      - mysql_root_password
      - mysql_openmrs_password
    environment:
      MYSQL_DATABASE: openmrs
      MYSQL_USER: ${OMRS_DB_USER:-openmrs}
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_openmrs_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  mysql_openmrs_password:
    file: ./secrets/mysql_openmrs_password.txt
