name: Daily Docker Cleanup and Redeploy

on:
  schedule:
    - cron: "0 3 * * *" # Runs at 3 AM daily
  workflow_dispatch:

jobs:
  cleanup-and-redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_DEV }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H hii1sc-dev.inf.pucp.edu.pe >> ~/.ssh/known_hosts

      - name: Connect to server via SSH and run cleanup tasks
        run: |
          ssh -i ~/.ssh/id_rsa -o ServerAliveInterval=60 -o ServerAliveCountMax=3 u.hsc.dev@hii1sc-dev.inf.pucp.edu.pe << 'EOF'
            set -e  # Exit on any error

            cd ~/peruHCE-distro-referenceapplication

            echo "Checking disk space..."
            df -h

            echo "Checking memory..."
            free -m

            echo "Stopping and removing containers..."
            docker compose down --volumes --remove-orphans

            echo "Removing Docker images..."
            docker rmi -f $(docker images -q) || true

            echo "Pruning Docker volumes..."
            docker volume prune -f

            echo "Pruning Docker builder cache..."
            docker builder prune -a --force

            echo "Pulling latest code..."
            git pull origin deploy

            echo "Building and starting containers..."
            docker compose up -d --build
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
