name: Daily Docker Cleanup and Redeploy

on:
  schedule:
    - cron: "0 3 * * *" # Esto ejecutará el pipeline a las 3 AM todos los días
  workflow_dispatch: # Agrega esto para permitir ejecución manual

jobs:
  cleanup-and-redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_DEV }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H hii1sc-dev.inf.pucp.edu.pe >> ~/.ssh/known_hosts

      - name: Connect to server via SSH and run cleanup tasks
        run: |
          ssh -i ~/.ssh/id_rsa u.hsc.dev@hii1sc-dev.inf.pucp.edu.pe << 'EOF'

            cd ~/peruHCE-distro-referenceapplication

            docker compose down --volumes --remove-orphans

            docker rmi -f $(docker images -q)

            docker volume prune -f

            docker builder prune -a --force

            git pull origin deploy

            docker compose up -d --build
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_DEV }} # La clave privada SSH debe ser almacenada como secret en GitHub
